image: node:16

pipelines:
  default:
    - step:
        name: Build and Deploy to S3
        script:
          # Install AWS CLI
          - apt-get install -y python3-pip
          - pip3 install awscli

          # Configure AWS CLI with your AWS credentials
          - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          - aws configure set default.region $AWS_DEFAULT_REGION

          # Sync build to S3 bucket
          - aws s3 sync build/ s3://innercircleprints.com/
          - aws cloudfront create-invalidation --distribution-id EV4QAYE76JU7C --paths "/*"


